apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mfc.fullname" . }}-configmap-nginx
data:
  config: |-
    server {
        listen 80;

        location / {
            alias /var/www/html/;
        }
    }
